version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: FrontendDockerfile
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - velflix_network

  backend:
    build:
      context: .
      dockerfile: BackendDockerfile
    container_name: backend
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - velflix_network
    command: ["sh", "-c", "composer install && php artisan key:generate && php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: velflix
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - velflix_network

volumes:
  db_data:

networks:
  velflix_network:
