version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    env_file: 
      - .env
    ports:
      - "3000:3000"

  backend:
    image: php:8.1
    container_name: backend
    working_dir: /app
    env_file: 
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: ["sh", "-c", "apt-get update && apt-get install -y curl git unzip libpq-dev libzip-dev && docker-php-ext-install pdo pdo_mysql zip && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install && php artisan key:generate && php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: velflix
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

